spring.application.name=backend

spring.mongodb.uri=mongodb://vigilant:vigilant@localhost:27017/vigilant?authSource=admin

admin.username=admin
admin.password=changeme

jwt.secret=change-this-secret-to-something-long-and-random
jwt.expiration=86400000
